### ISSUE TITLE
[1.15.2, possibly earlier versions] Diamond shards drop when silk touching coal ores.

### ISSUE THREAD

**Issue by brisingraerowing** [Brian-Wuest/MC-Repurpose#31]
This allows for infinite diamond shards as you can keep placing and silk touching the ores to get more. It's grindy but very exploitable.

Repurpose 1.2.0.0

**Comment by Brian-Wuest** [comment]
Thanks for bringing that up. The fix was pretty easy to implement.

Are there any other blocks or additional drops that Repurpose does that should get fixed. 

The only one I can see being a "problem" would be some of the drops from dirt just because you can get infinite food or bonemeal or clay balls.

**Comment by Brian-Wuest** [comment]
hmm....now that I say that; I will probably just update all of them so if they use silk touch that they don't drop these additional things.

**Comment by Brian-Wuest** [comment]
This will be fixed with 1.1.0.1 and 1.2.0.1 for minecraft versions 1.14.4 and 1.15.2 respectively. 

They have been uploaded to curseforge and will become available when they get through the review process.

Closing issue.

Thank you!
