### ISSUE TITLE
Idea for home command in the Nether and the End

### ISSUE THREAD

**Issue by brisingraerowing** [Brian-Wuest/MC-Repurpose#8]
For the nether and the end, would it be possible to make the home command teleport you back to where you entered the dimension (e.g. the nether portal you came out of)? That would be useful if you went exploring and couldn't find the portal you came through again.

**Comment by Brian-Wuest** [comment]
I can look into it. It was easy in the overworld because the bed locationsis saved with the player.

I could add something similar for other dimensions.

Thanks for the idea!

**Comment by Brian-Wuest** [comment]
I have an update on this.

I am using Forge's Capability system so I can save the "Home" location for each dimension the player enters.

The "Home" location is based on the position the player appears when they enter the dimension. 

For the **Nether**, this means you will appear in the Nether Portal frame you entered from. This could cause you to teleport instantly if in Creative Mode. You will always be teleported to the portal frame you entered the Nether from. This could possibly be dangerous if the portal frame is no longer there due to Ghasts or other things.

For the **End**, this means you will appear on the obsidian platform you entered the End from. So make sure you made and kept a bridge to the main End island.

For the **Overworld**, you will still appear next to your bed,

This functionality _should_ work for Mod created dimensions as these positions are based on Dimension ID. However, the safety and reliability of the positions in these custom dimensions is up to the original mod developer. This home command will just place you were you entered :smile: 

If the non-Overworld dimension's entrance is blocked (such as the Nether portal was destroyed and then filled with gravel while you were in the Nether) you will get a message stating as such and that you need to find another way out.

I am going to do some final testing and cleaning up of the code before I release this change.

**Comment by brisingraerowing** [comment]
I usually play in creative, so no issues with monsters.

As for the end, I often appear inside the end island, instead of next to it.

**Comment by Brian-Wuest** [comment]
Ah ok. It was just in the flat world I was in where I was far away from the main island.

**Comment by Brian-Wuest** [comment]
This request has been implemented in release 1.10.2.7 which is now available on CurseForge.

Thanks!
